import { AfterContentInit, EventEmitter, OnChanges, OnDestroy, OnInit, SimpleChanges } from '@angular/core';
export declare const SIDEBAR_POSITION: {
    Left: string;
    Right: string;
    Top: string;
    Bottom: string;
};
export default class Sidebar implements OnInit, AfterContentInit, OnChanges, OnDestroy {
    private _document;
    open: boolean;
    openChange: EventEmitter<boolean>;
    position: string;
    closeOnClickOutside: boolean;
    showOverlay: boolean;
    animate: boolean;
    defaultStyles: boolean;
    sidebarClass: string;
    overlayClass: string;
    ariaLabel: string;
    onOpen: EventEmitter<null>;
    onClose: EventEmitter<null>;
    private _elSidebar;
    private _closeDirectives;
    private _visibleSidebarState;
    private _onClickOutsideAttached;
    private _focusableElementsString;
    private _focusableElements;
    private _focusedBeforeOpen;
    constructor(_document: HTMLDocument);
    ngOnInit(): void;
    ngAfterContentInit(): void;
    ngOnChanges(changes: SimpleChanges): void;
    ngOnDestroy(): void;
    private _setvisibleSidebarState();
    private _open();
    private _close();
    private _manualClose();
    private _getFocusableElements();
    private _setFocusToFirstItem();
    private _trapFocus(e);
    private _setFocused(open);
    private _initCloseOnClickOutside();
    private _destroyCloseOnClickOutside();
    private _onClickOutside(e);
}
